ALTER TABLE "User" ADD COLUMN "isSuperAdmin" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Tenant" ADD COLUMN "subscriptionPackage" TEXT NOT NULL DEFAULT 'STARTER';
ALTER TABLE "Tenant" ADD COLUMN "maxStations" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Tenant" ADD COLUMN "maxTanks" INTEGER NOT NULL DEFAULT 3;
ALTER TABLE "Tenant" ADD COLUMN "maxPumps" INTEGER NOT NULL DEFAULT 3;
